
export const ADD_TO_BROWSER_HISTORY = "ADD_TO_BROWSER_HISTORY"
export const REPLACE_BROWSER_HISTORY_ITEM = "REPLACE_BROWSER_HISTORY_ITEM"
export const GO_FOWARD_TO_BROWSER_ITEM = "GO_FORWARD_TO_BROWSER_ITEM"
export const GO_BACK_TO_BROWSER_ITEM = "GO_BACK_TO_BROWSER_ITEM"
export const RESET_BROWSER_HISTORY = "RESET_BROWSER_HISTORY"

