
export const FETCH_ALERTS_CATS_REQUEST = "FETCH_ALERTS_CATS_REQUEST"
export const FETCH_ALERTS_CATS_SUCCESS = "FETCH_ALERTS_CATS_SUCCESS"
export const FETCH_ALERTS_CATS_FAILURE = "FETCH_ALERTS_CATS_FAILURE"
export const SET_ALERTS_CATEGORY  = "SET_ALERTS_CATEGORY"



