
export const FETCH_ALERTS_LIST_REQUEST = "FETCH_ALERTS_LIST_REQUEST"
export const FETCH_ALERTS_LIST_SUCCESS = "FETCH_ALERTS_LIST_SUCCESS"
export const FETCH_ALERTS_LIST_FAILURE = "FETCH_ALERTS_LIST_FAILURE"
export const SET_ALERT_ID = "SET_ALERT_ID"



