// export const FETCH_USER_PROFILE_SETTINGS_REQUEST = "FETCH_USER_PROFILE_SETTINGS_REQUEST"
// export const FETCH_USER_PROFILE_SETTINGS_SUCCESS = "FETCH_USER_PROFILE_SETTINGS_SUCCESS"
// export const FETCH_USER_PROFILE_SETTINGS_FAILURE = "FETCH_USER_PROFILE_SETTINGS_FAILURE"
export const TEST = "TEST"

