
export const FETCH_SAVED_JOBS_LIST_REQUEST = "FETCH_SAVED_JOBS_LIST_REQUEST"
export const FETCH_SAVED_JOBS_LIST_SUCCESS = "FETCH_SAVED_JOBS_LIST_SUCCESS"
export const FETCH_SAVED_JOBS_LIST_FAILURE = "FETCH_SAVED_JOBS_LIST_FAILURE"

export const DELETE_SAVED_JOB_REQUEST = "DELETE_SAVED_JOB_REQUEST"
export const DELETE_SAVED_JOB_SUCCESS = "DELETE_SAVED_JOB_SUCCESS"
export const DELETE_SAVED_JOB_FAILURE = "DELETEDELETE_SAVED_JOB_FAILURE"


