
export const SEND_CONTACT_DATA_REQUEST = "SEND_CONTACT_DATA_REQUEST"
export const SEND_CONTACT_DATA_SUCCESS = "SEND_CONTACT_DATA_SUCCESS"
export const SEND_CONTACT_DATA_FAILURE = "SEND_CONTACT_DATA_FAILURE" 

export const UNSET_NOTIFICATION_DISPLAY = "UNSET_NOTIFICATION_DISPLAY"

