
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST'
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE' 

export const SEND_USER_AVATAR_UPDATE_REQUEST = "SEND_USER_AVATAR_UPDATE_REQUEST"
export const SEND_USER_AVATAR_UPDATE_SUCCESS = "SEND_USER_AVATAR_UPDATE_SUCCESS"
export const SEND_USER_AVATAR_UPDATE_FAILURE = " SEND_USER_AVATAR_UPDATE_FAILURE"


export const SEND_USER_PROFILE_UPDATE_REQUEST = "SEND_USER_PROFILE_UPDATE_REQUEST"
export const SEND_USER_PROFILE_UPDATE_SUCCESS = "SEND_USER_PROFILE_UPDATE_SUCCESS"
export const SEND_USER_PROFILE_UPDATE_FAILURE = " SEND_USER_PROFILE_UPDATE_FAILURE" 

export const SEND_USER_ACCOUNT_DELETE_REQUEST = "SEND_USER_ACCOUNT_DELETE_REQUEST"
export const SEND_USER_ACCOUNT_DELETE_SUCCESS = "SEND_USER_ACCOUNT_DELETE_SUCCESS"
export const SEND_USER_ACCOUNT_DELETE_FAILURE = "SEND_USER_ACCOUNT_DELETE_FAILURE" 

export const UNSET_IS_PROFILE = "UNSET_IS_PROFILE"
export const UNSET_NOTIFICATION_DISPLAY = "UNSET_NOTIFICATION_DISPLAY"





